import {
  Book,
  Globe,
  FileText,
  BookOpen,
  Newspaper,
  FileImage,
  Eye,
  FileUp,
  Archive,
} from "lucide-react";

export const materialTypes = [
  {
    value: "book",
    label: "Book",
    icon: <Book size={16} />,
    color: "bg-orange-100 text-orange-800",
  },
  {
    value: "website",
    label: "Website/URL",
    icon: <Globe size={16} />,
    color: "bg-blue-100 text-blue-800",
  },
  {
    value: "digital",
    label: "Digital Content",
    icon: <FileText size={16} />,
    color: "bg-purple-100 text-purple-800",
  },
  {
    value: "informational",
    label: "Informational",
    icon: <Newspaper size={16} />,
    color: "bg-green-100 text-green-800",
  },
  {
    value: "creative",
    label: "Creative Work",
    icon: <BookOpen size={16} />,
    color: "bg-pink-100 text-pink-800",
  },
  {
    value: "traditional",
    label: "Traditional Print",
    icon: <FileImage size={16} />,
    color: "bg-gray-100 text-gray-800",
  },
];

export const categoryOptions = {
  book: [
    { value: "manual", label: "Manual" },
    { value: "textbook", label: "Textbook" },
    { value: "reference", label: "Reference" },
    { value: "other", label: "Other" },
  ],
  website: [
    { value: "article", label: "Article" },
    { value: "blog", label: "Blog" },
    { value: "tutorial", label: "Tutorial" },
    { value: "documentation", label: "Documentation" },
  ],
  digital: [
    { value: "ebook", label: "E-Book" },
    { value: "pdf", label: "PDF" },
    { value: "presentation", label: "Presentation" },
    { value: "interactive", label: "Interactive" },
  ],
  informational: [
    { value: "manual", label: "Manual" },
    { value: "article", label: "Article" },
    { value: "report", label: "Report" },
    { value: "whitepaper", label: "Whitepaper" },
    { value: "research", label: "Research" },
  ],
  creative: [
    { value: "novel", label: "Novel" },
    { value: "comic", label: "Comic" },
    { value: "poem", label: "Poem" },
    { value: "shortstory", label: "Short Story" },
    { value: "script", label: "Script" },
  ],
  traditional: [
    { value: "book", label: "Printed Book" },
    { value: "magazine", label: "Magazine" },
    { value: "newspaper", label: "Newspaper" },
    { value: "journal", label: "Journal" },
    { value: "brochure", label: "Brochure" },
  ],
};

export const statusOptions = [
  {
    value: "published",
    label: "Published",
    color: "bg-green-100 text-green-800 border-green-200",
    icon: <Eye size={14} />,
    bgColor: "bg-green-50",
  },
  {
    value: "draft",
    label: "Draft",
    color: "bg-yellow-100 text-yellow-800 border-yellow-200",
    icon: <FileUp size={14} />,
    bgColor: "bg-yellow-50",
  },
  {
    value: "archived",
    label: "Archived",
    color: "bg-gray-100 text-gray-800 border-gray-200",
    icon: <Archive size={14} />,
    bgColor: "bg-gray-50",
  },
];

export const initialMaterials = [
  {
    id: 1,
    title: "React Programming Guide",
    type: "book",
    category: "manual",
    author: "John Doe",
    description:
      "Complete guide to React programming with modern practices and examples.",
    content: "",
    url: "",
    status: "published",
    dateAdded: "2024-01-15",
    views: 1245,
    tags: ["react", "programming", "guide", "javascript", "frontend"],
    images: [
      {
        id: "img1",
        url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=300&fit=crop",
        name: "react-cover.jpg",
        size: 204800,
        type: "image/jpeg",
        isCover: true,
        uploadedAt: "2024-01-14T10:30:00Z",
      },
    ],
  },
  {
    id: 2,
    title: "Modern Web Development Blog",
    type: "website",
    category: "article",
    author: "Jane Smith",
    description: "Latest trends and best practices in modern web development.",
    content: "",
    url: "https://example.com/blog",
    status: "published",
    dateAdded: "2024-01-10",
    views: 890,
    tags: ["web", "development", "trends"],
    images: [],
  },
  {
    id: 3,
    title: "Digital Art Manual",
    type: "digital",
    category: "manual",
    author: "Art Studio",
    description: "Step-by-step digital art creation techniques and tools.",
    content: "Digital content here...",
    url: "",
    status: "draft",
    dateAdded: "2024-01-05",
    views: 320,
    tags: ["art", "digital", "tutorial", "design"],
    images: [
      {
        id: "img3",
        url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w-400&h=300&fit=crop",
        name: "digital-art.jpg",
        size: 307200,
        type: "image/jpeg",
        isCover: true,
        uploadedAt: "2024-01-04T14:20:00Z",
      },
    ],
  },
  {
    id: 4,
    title: "The Great Adventure",
    type: "creative",
    category: "novel",
    author: "Author Writer",
    description:
      "A thrilling adventure novel set in a fantasy world with complex characters.",
    content: "Novel content here...",
    url: "",
    status: "published",
    dateAdded: "2024-01-03",
    views: 1567,
    tags: ["fiction", "adventure", "novel", "fantasy"],
    images: [
      {
        id: "img4",
        url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop",
        name: "book-cover.jpg",
        size: 256000,
        type: "image/jpeg",
        isCover: true,
        uploadedAt: "2024-01-02T09:15:00Z",
      },
    ],
  },
  {
    id: 5,
    title: "Technical Documentation",
    type: "informational",
    category: "manual",
    author: "Tech Corp",
    description: "Comprehensive API documentation with examples and use cases.",
    content: "Technical content...",
    url: "",
    status: "published",
    dateAdded: "2024-01-12",
    views: 540,
    tags: ["technical", "documentation", "api", "backend"],
    images: [],
  },
  {
    id: 6,
    title: "Poetry Collection 2024",
    type: "creative",
    category: "poem",
    author: "Poet Writer",
    description: "Modern poetry collection exploring contemporary themes.",
    content: "Poetry content...",
    url: "",
    status: "archived",
    dateAdded: "2023-12-20",
    views: 210,
    tags: ["poetry", "creative", "literature"],
    images: [
      {
        id: "img6",
        url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
        name: "poetry-cover.jpg",
        size: 198000,
        type: "image/jpeg",
        isCover: true,
        uploadedAt: "2023-12-19T16:45:00Z",
      },
    ],
  },
];

export const initialArchiveHistory = [
  {
    id: 1,
    materialId: 6,
    title: "Poetry Collection 2024",
    archivedBy: "Admin User",
    archivedDate: "2023-12-20",
    reason: "Seasonal content rotation",
    previousStatus: "published",
  },
  {
    id: 2,
    materialId: 7,
    title: "Old Marketing Guide",
    archivedBy: "Content Manager",
    archivedDate: "2023-11-15",
    reason: "Outdated information",
    previousStatus: "published",
  },
  {
    id: 3,
    materialId: 8,
    title: "Legacy API Docs",
    archivedBy: "Tech Lead",
    archivedDate: "2023-10-05",
    reason: "API version deprecated",
    previousStatus: "published",
  },
];

